trigger:
- main

pool:
  name: may-pool

stages:

- stage: Build
  displayName: Build React App
  jobs:
  - job: BuildJob
    steps:

    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: Install Node.js

    - script: |
        rm -rf node_modules package-lock.json
        npm install --legacy-peer-deps
      displayName: Install Dependencies

    - script: |
        npm run build
      displayName: Build App

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'build'
        artifactName: 'app'