trigger:
- main

pool:
  name: may-pool

steps:


# 1. SOURCE CODE

- checkout: self


# 2. NODE INSTALL

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: Install Node.js


# 3. INSTALL DEPENDENCIES

- script: npm install
  displayName: Install Dependencies


# 4. BUILD REACT APP

- script: npm run build
  displayName: Build App


# 5. DEPLOY TO VM (SSH)

- task: SSH@0
  inputs:
    sshEndpoint: 'vm-ssh'
    runOptions: 'commands'
    commands: |
      sudo rm -rf /var/www/chat-application/*
      sudo cp -r /home/azureuser/chat-application/build/* /var/www/chat-application/
      sudo systemctl restart nginx
  displayName: Deploy to VM